"""Render the M0 audit as Markdown from ``audit.json``. Nothing here computes or types a count."""

from __future__ import annotations

from typing import Any


def _fmt(x: Any) -> str:
    if x is None:
        return "—"
    if isinstance(x, float):
        return f"{x:.3g}"
    return str(x)


def _q(d: dict[str, Any]) -> str:
    if not d.get("n"):
        return "no data"
    return (f"n={d['n']}, median {_fmt(d['median'])} (IQR {_fmt(d['q25'])}–{_fmt(d['q75'])}, "
            f"range {_fmt(d['min'])}–{_fmt(d['max'])})")


def _table(rows: list[dict[str, Any]], cols: list[str]) -> str:
    out = ["| " + " | ".join(cols) + " |", "| " + " | ".join("---" for _ in cols) + " |"]
    out += ["| " + " | ".join(_fmt(r.get(c)) for c in cols) + " |" for r in rows]
    return "\n".join(out)


def _kv(d: dict[str, Any]) -> str:
    return ", ".join(f"{k}: {_fmt(v)}" for k, v in d.items())


def render(r: dict[str, Any], target_rows: list[dict[str, Any]]) -> str:
    c, q, p, t, s = r["counts"], r["quality"], r["pairs"], r["targets"], r["stimulus"]
    sel, go = r["split_selection"], r["go_no_go"]
    lines = [
        f"# M0 data audit ({r['audit_version']})",
        "",
        "> Generated by `python -m occamworm.analysis audit` from "
        f"`data/normalized/{r['dataset']}` (manifest sha256 `{r['dataset_manifest_sha256'][:16]}…`) and "
        "`configs/datasets/eligibility.json`, code revision "
        f"`{(r['code_revision'] or 'unknown')[:12]}`. Do not edit by hand. Spec: §2.3.",
        "",
        f"**Go/no-go: {go['decision']}.** {len(go['targets'])} targets meet the criterion under the chosen split "
        f"`{sel['chosen']}`.",
        "",
        "## Counts",
        "",
        f"- Animals {c['animals']}, recordings {c['recordings']}, sessions {c['sessions']}, trials {c['trials']}.",
        f"- Animals by genotype: {_kv(c['animals_by_genotype'])}. {c['genotype_coverage_note']}",
        f"- Animal identity: {c['animal_id_assumption']}.",
        f"- Trials by target code: {_kv(c['trials_by_target_code'])}.",
        f"- Identified stimulation targets: {c['identified_targets']} "
        f"({c['trials_with_identified_target']} trials).",
        f"- ROIs {c['rois']}; label status: {_kv(c['roi_label_status'])}.",
        "",
        "## Inclusion flowchart",
        "",
        "```mermaid",
        "flowchart TD",
        f"    A[\"{c['trials']} trials, {c['animals']} animals\"] --> B[\"{c['trials_with_identified_target']} "
        "trials with an identified target\"]",
        f"    B --> C[\"{t['identified_targets']} identified targets\"]",
        f"    C --> D[\"{t['eligible_targets']} eligible targets\"]",
        f"    D --> E[\"{t['eligible_with_responsive_pair']} with a responsive multi-animal pair\"]",
        f"    E --> F[\"{len(go['targets'])} covered by split {sel['chosen']}\"]",
    ]
    for i, (reason, n) in enumerate(t["exclusions"].items()):
        lines.append(f"    C -. \"{n} excluded\" .-> X{i}[\"{reason}\"]")
    lines += [
        "```",
        "",
        "## Data quality",
        "",
        f"- Autoresponses: {q['trials_with_autoresponse']} trials have one; {q['autoresponses_valid']} are valid "
        f"(>= {r['config']['autoresponse_min_valid_fraction']} of window samples tracked); "
        f"{q['autoresponse_window_amplitude_defined']} have a defined response amplitude.",
        f"- Sham events: {q['sham_events']}. {q['sham_note']}",
        f"- Window samples valid: {q['window_samples_valid_fraction']:.1%} of {q['window_samples']}; windows "
        f"without a usable baseline {q['windows_without_baseline']}; without a response amplitude "
        f"{q['windows_without_response_amplitude']}.",
        f"- ROIs with uncertain identity (not a unique name): {q['uncertain_identity_rois']}.",
        f"- Trial QC flags: {_kv(q['trial_qc_flags'])}.",
        "",
        "## Stimulus and timing",
        "",
        f"- Sampling {s['sampling_rate_hz']:.3g} Hz ({s['volume_interval_s']} s volumes). Window: "
        f"{s['window']['pre_volumes']} volumes before, {s['window']['post_volumes']} from the stimulation; amplitude "
        f"is the mean dF/F over offsets {s['window']['response_offsets']}.",
        f"- Stimulus duration known for {s['stimulus_duration_s_known']} trials, amplitude for "
        f"{s['stimulus_amplitude_known']} (the pulse rate is not exported).",
        f"- Optogenetics: {_kv(s['optogenetics_type'])}; pulses {_kv(s['optogenetics_n_pulses'])}; trains "
        f"{_kv(s['optogenetics_n_trains'])}.",
        f"- Inter-stimulus interval (s): {_q(s['inter_stimulus_interval_s'])}.",
        f"- Response volumes before the next stimulation: {_q(s['post_window_volumes_before_next_stim'])}.",
        f"- Stimulations per recording: {_q(s['stimulations_per_recording'])}; recording duration (s): "
        f"{_q(s['recording_duration_s'])}.",
        f"- Trials whose previous target had the same label: {s['trials_whose_previous_target_label_is_the_same']}.",
        "",
        "## Within-recording drift",
        "",
        "Per-animal least-squares slopes, mean across animals with an animal-level bootstrap 95% interval.",
        "",
    ]
    for name, d in r["drift"].items():
        ci = d["ci95"]
        interval = f"{_fmt(ci[0])} to {_fmt(ci[1])}" if ci else "—"
        lines.append(f"- `{name}`: {_fmt(d['mean'])} {d['unit']} (95% CI {interval}, {d['n_animals']} animals).")
    vd = p["variance_decomposition"]
    lines += [
        "",
        "## Pairs and replication",
        "",
        f"- Observed (identified target, identified responder) pairs: {p['pairs_observed']}.",
        f"- Pairs by number of animals: {_kv(p['pairs_by_animal_count'])}.",
        f"- Pairs by number of trials: {_kv(p['pairs_by_trial_count'])}.",
        "- Pairs with at least k animals: "
        + ", ".join(f"k={k}: {n} ({p['fraction_pairs_with_min_animals'][k]:.1%})"
                    for k, n in p["pairs_with_min_animals"].items()) + ".",
        f"- Distinct responders per target: {_q(t['distinct_responders_per_target'])}; observed in >= "
        f"{r['config']['responder_min_animals']} animals: {_q(t['multi_animal_responders_per_target'])}.",
        f"- Trial-to-trial vs animal-to-animal variance ({vd['pairs_estimable']} estimable pairs): median "
        f"between-animal fraction {_fmt(vd['median_between_animal_fraction'])}; pooled within "
        f"{_fmt(vd['pooled_within_animal_variance'])}, between {_fmt(vd['pooled_between_animal_variance'])}. "
        f"{vd['note']}",
        "",
        "## Indicator",
        "",
    ]
    ind = r["indicator"]
    k = ind["autoresponse_kinetics"]
    lines += [
        f"- Indicator: {ind['name']}; strain {ind['strain']}. Source: {ind['reference']}.",
        f"- {ind['published_kinetics_note']}",
        f"- Strong autoresponses (peak >= {r['config']['autoresponse_min_peak_over_noise']}× pre-stimulus SD): "
        f"{k['n_strong_autoresponses']}. Peak latency (s): {_q(k['peak_latency_s'])}. Time to half peak (s): "
        f"{_q(k['time_to_half_peak_s'])}. Half-decay after peak (s): {_q(k['half_decay_after_peak_s'])}; "
        f"censored {k['half_decay_censored']}. {k['note']}",
        "",
        "## Neuron ID intersection",
        "",
    ]
    ix = r["id_intersection"]
    if ix["status"] == "computed":
        lines.append(f"- Atlas {ix['atlas_ids']}, anatomy {ix['anatomy_ids']}, molecular {ix['molecular_ids']}; "
                     f"atlas∩anatomy {ix['atlas_and_anatomy']}, atlas∩molecular {ix['atlas_and_molecular']}, "
                     f"all three {ix['all_three']}.")
        if ix["atlas_not_in_anatomy"]:
            lines.append(f"- Atlas IDs absent from the anatomy: {', '.join(ix['atlas_not_in_anatomy'])}.")
    else:
        lines.append(f"- {ix['status']} ({ix['atlas_ids']} atlas IDs).")
    lines += [
        "",
        "## Split scheme selection",
        "",
        f"Rule: {sel['rule']}. Chosen: **{sel['chosen']}**.",
        "",
        _table(sel["schemes"], ["name", "outer", "n_outer_folds", "inner_folds", "eligible_targets_covered",
                                "eligible_targets_tested_without_inner_coverage", "median_test_animals_per_target"]),
        "",
        "Per-target fold coverage: `fold_coverage.parquet`.",
        "",
        "## Eligible targets",
        "",
        _table([x for x in target_rows if x["eligible"]],
               ["target", "n_animals", "n_animals_valid_autoresponse", "n_trials", "responders_multi_animal",
                "responsive_pairs"]),
        "",
        f"Go/no-go criterion: {go['criterion']}. Targets: {', '.join(go['targets']) or 'none'}.",
        "",
    ]
    return "\n".join(lines)
